config/routes.rb
Rails.application.routes.draw do

  namespace :iml do
    resources :points, :only => [:index, :update, :edit, :show]
    resources :cities, :only => [:index, :update, :edit, :show]
  end

  namespace :bidspirit do
    resources :tasks
  end

  resources :gdrives

  resources :settings, :only => [:index, :update, :edit]

  namespace :oldbook do
    resources :categories, :only => [:index, :edit, :update, :show]
    resources :files, :only => [:destroy]
    resources :tasks
  end

  namespace :artelbook do
    resources :categories, :only => [:index, :edit, :update, :show]
    resources :files, :only => [:destroy]
    resources :tasks
  end

  namespace :alib do
    resources :tasks
  end

  namespace :newauction do
    resources :tasks
  end

  namespace :ebay do
    resources :tasks
  end

  namespace :notifi do
    resources :templates
    resources :contents, :only => [:destroy]
  end

  namespace :parse do
    resources :dbs
    resources :tasks
  end

  namespace :avito do
    resources :accounts
    resources :postings
    resources :tasks
    resources :finds
  end

  devise_for :users
  resources :images, :only => [:index, :create]
  resources :roles

  root  'static_page#main'
  post  'beta' => 'feed_back#beta'

  post  'api/avito' => 'api#avito'
  get   'api/avito' => 'api#avito'

  post  'api/test' => 'api#test'
  get   'api/test' => 'api#test'

  post  'tst' => 'api#txt'
  get   'tst' => 'api#txt'

  get   'test' => 'static_page#test'

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/alib.rb
module Alib
  def self.table_name_prefix
    'alib_'
  end
end

app/models/artelbook.rb
module Artelbook
  def self.table_name_prefix
    'artelbook_'
  end
end

app/models/avito.rb
module Avito
  def self.table_name_prefix
    'avito_'
  end
end

app/models/bidspirit.rb
module Bidspirit
  def self.table_name_prefix
    'bidspirit_'
  end
end

app/models/ebay.rb
module Ebay
  def self.table_name_prefix
    'ebay_'
  end
end

app/models/gdrive.rb
class Gdrive < ActiveRecord::Base
  has_many :avito_tasks,     :class_name => Avito::Task
  has_many :newauction_task, :class_name => Newauction::Task
  has_many :ebay_task,       :class_name => Ebay::Task
  has_many :alib_task,       :class_name => Alib::Task
  has_many :bidspirit_task,  :class_name => Bidspirit::Task
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
end

app/models/iml.rb
module Iml
  def self.table_name_prefix
    'iml_'
  end
end

app/models/iml/city.rb
class Iml::City < ActiveRecord::Base
  has_many :points
end

app/models/iml/point.rb
class Iml::Point < ActiveRecord::Base
  belongs_to :city


  scope :my_order, -> { order(city_id: :asc).order(metro: :asc).order(address_formatted: :asc) }
end

app/models/newauction.rb
module Newauction
  def self.table_name_prefix
    'newauction_'
  end
end

app/models/notifi.rb
module Notifi
  def self.table_name_prefix
    'notifi_'
  end
end

app/models/oldbook.rb
module Oldbook
  def self.table_name_prefix
    'oldbook_'
  end
end

app/models/parse.rb
module Parse
  def self.table_name_prefix
    'parse_'
  end
end

app/models/role.rb
class Role < ActiveRecord::Base

  has_many :users
end

app/models/setting.rb
class Setting < ActiveRecord::Base

  def self.get(s)
    setting = Setting.find_by(:name => s)

    if setting.nil?
      v=false
    else
      case setting.t
      when "integer"
        v = setting.v.to_i
      when "string"
        v = setting.v
      when "text"
        v = setting.v
      when "json"
        v = setting.vh
      else
        v = nil
      end

      v
    end
  end


  def self.set(s,v)
    setting = Setting.find_by(:name => s)

    if setting.nil?
      false
    else
      case setting.t
      when "integer"
        setting.v = v
      when "string"
        setting.v = v
      when "text"
        setting.v = v
      when "json"
        setting.vh = v
      else

      end

      setting.save
    end


  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :invitable, :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  #:registerable

  devise :database_authenticatable, :recoverable, :confirmable, :validatable, :invitable, :invite_for => 2.weeks
  
  has_many :avito_tasks,    :class_name => Avito::Task
  has_many :avito_postings, :class_name => Avito::Posting
  has_many :avito_accounts, :class_name => Avito::Account
  has_many :avito_finds,    :class_name => Avito::Find
  
  has_many :notifi_templates, :class_name => Notifi::Template
  
  has_many :newauction_task, :class_name => Newauction::Task
  has_many :ebay_task,       :class_name => Ebay::Task
  has_many :alib_task,       :class_name => Alib::Task

  has_many :images
  
  belongs_to :role

end

app/models/vk.rb
module Vk
  def self.table_name_prefix
    'vk_'
  end
end

app/controllers/iml/cities_controller.rb
class Iml::CitiesController < ApplicationController
  before_action :set_iml_city, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  respond_to :html

  def index
    @iml_cities = Iml::City.all
    respond_with(@iml_cities)
  end

  def show
    respond_with(@iml_city)
  end

  def new
    @iml_city = Iml::City.new
    respond_with(@iml_city)
  end

  def edit
  end

  def create
    @iml_city = Iml::City.new(city_params)
    @iml_city.save
    respond_with(@iml_city)
  end

  def update
    @iml_city.update(city_params)
    respond_with(@iml_city)
  end

  def destroy
    @iml_city.destroy
    respond_with(@iml_city)
  end

  private
    def set_iml_city
      @iml_city = Iml::City.find(params[:id])
    end

    def iml_city_params
      params.require(:iml_city).permit(:name, :prefix, :zoom, :lat, :lon, :geo)
    end
end

app/controllers/iml/points_controller.rb
class Iml::PointsController < ApplicationController
  before_action :set_iml_point, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:inidex]

  respond_to :html

  def index
    case params[:gen]
    when "msk"
      @iml_points = Iml::City.find_by(:prefix => "/Moscow").points.my_order
      render layout: 'clear', template: '/iml/points/table'

    when 'spb'
      @iml_points = Iml::City.find_by(:prefix => "/Saint_Petersburg").points.my_order
      render layout: 'clear', template: '/iml/points/table'
    when 'oth'
      ids = Iml::City.where(:prefix => ["?Moscow","/Saint_Petersburg" ]).map{|i| i.id}
      @iml_points = Iml::Point.where.not(city_id: ids).my_order
      render layout: 'clear', template: '/iml/points/table2'
    else
      @iml_points = Iml::Point.my_order.all
      respond_with(@iml_points)
    end

  end

  def show
    respond_with(@iml_point)
  end

  def new
    @iml_point = Iml::Point.new
    respond_with(@iml_point)
  end

  def edit
  end

  def create
    @iml_point = Iml::Point.new(point_params)
    @iml_point.save
    respond_with(@iml_point)
  end

  def update
    @iml_point.update(point_params)
    respond_with(@iml_point)
  end

  def destroy
    @iml_point.destroy
    respond_with(@iml_point)
  end

  private
    def set_iml_point
      @iml_point = Iml::Point.find(params[:id])
    end

    def iml_point_params
      params.require(:iml_point).permit(:name, :link, :zoom, :address, :path, :time, :photo, :metro, :lat, :lon, :geo, :city_id)
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
    <div data-alert class="alert-box alert radius">
      <ul class="square">
        #{messages}
      </ul>
      <a href="#" class="close">&times;</a>
    </div>
    HTML



    html.html_safe
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/iml/cities_helper.rb
module Iml::CitiesHelper
end

app/helpers/iml/points_helper.rb
module Iml::PointsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/iml/points/_form.html.haml
= form_for @iml_point do |f|
  - if @iml_point.errors.any?
    #error_explanation
      %h2= "#{pluralize(@iml_point.errors.count, "error")} prohibited this iml_point from being saved:"
      %ul
        - @iml_point.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :link
    = f.text_field :link
  .field
    = f.label :zoom
    = f.text_field :zoom
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :path
    = f.text_field :path
  .field
    = f.label :time
    = f.text_field :time
  .field
    = f.label :photo
    = f.text_field :photo
  .field
    = f.label :metro
    = f.text_field :metro
  .field
    = f.label :lat
    = f.text_field :lat
  .field
    = f.label :lon
    = f.text_field :lon
  .field
    = f.label :geo
    = f.text_field :geo
  .field
    = f.label :city_id
    = f.number_field :city_id
  .actions
    = f.submit 'Save'

app/views/iml/points/edit.html.haml
%h1 Editing iml_point

= render 'form'

= link_to 'Show', @iml_point
\|
= link_to 'Back', iml_points_path

app/views/iml/points/index.html.haml
%h1
  =t('iml_points')
  %small
    = I18n.localize Iml::City.find_by(prefix: "/Moscow").updated_at, :format => :long

%ul
  %li
    %a{:href=> '/iml/points?gen=msk'} Москва и область
  %li
    %a{:href=> '/iml/points?gen=spb'} СПБ и область
  %li
    %a{:href=> '/iml/points?gen=oth'} Остальные города



%table
  %thead
    %tr
      %th= t 'address'
      %th= t 'times'
      %th= t 'metro'
      %th
      %th

  %tbody
    - city_id = 0
    - @iml_points.each do |iml_point|
      - if iml_point.city_id != city_id
        - city_id = iml_point.city_id
        %tr
          %th{:colspan=> 6, :class=>'group'}
            %a{:href => "http://iml.ru/places#{iml_point.city.prefix}"}
              = iml_point.city.name

      %tr
        %td
          %a{:href => "http://iml.ru/places#{iml_point.link}"}
            = iml_point.address_formatted
        %td= iml_point.time
        %td= iml_point.metro

        %td= link_to t('show'), iml_point
        %td= link_to t('edit'), edit_iml_point_path(iml_point)

app/views/iml/points/new.html.haml
%h1 New iml_point

= render 'form'

= link_to 'Back', iml_points_path

app/views/iml/points/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @iml_point.name
%p
  %b Link:
  = @iml_point.link
%p
  %b Zoom:
  = @iml_point.zoom
%p
  %b Address:
  = @iml_point.address

%p
  %b Address_formatted:
  = @iml_point.address_formatted

%p
  %b Path:
  = @iml_point.path
%p
  %b Time:
  = @iml_point.time
%p
  %b Photo:
  = @iml_point.photo
%p
  %b Metro:
  = @iml_point.metro
%p
  %b Lat:
  = @iml_point.lat
%p
  %b Lon:
  = @iml_point.lon
%p
  %b Geo:
  = @iml_point.geo
%p
  %b City:
  = @iml_point.city_id

= link_to 'Edit', edit_iml_point_path(@iml_point)
\|
= link_to 'Back', iml_points_path

app/views/iml/points/table.html.haml
%table.table-basket
  %tbody

    %tr
      %th
        %b Метро
      %th
        %b Адрес
      %th{:style=>"padding-right: 5px;"}
        %b Стоимость
      %th
        %b Время работы

    - @iml_points.each do |iml_point|
      %tr
        %td= iml_point.metro
        %td
          %a{:href => "http://iml.ru/places#{iml_point.link}", :target=>"_blank"}
            = iml_point.address_formatted
        %td
          .delivery
            %span
              Стоимость:
            100 руб.

        %td= iml_point.time

app/views/iml/points/table2.html.haml
%table.table-basket
  %tbody

    %tr

      %th
        %b Адрес
      %th{:style=>"padding-right: 5px;"}
        %b Стоимость
      %th
        %b Время работы

    - @iml_points.each do |iml_point|
      %tr
        %td
          %a{:href => "http://iml.ru/places#{iml_point.link}", :target=>"_blank"}
            = iml_point.address_formatted
        %td
          .delivery
            %span
              Стоимость:
            120 руб.

        %td= iml_point.time