config/routes.rb
Rails.application.routes.draw do

  namespace :iml do
    resources :points, :only => [:index, :update, :edit, :show]
    resources :cities, :only => [:index, :update, :edit, :show]
  end

  namespace :bidspirit do
    resources :tasks
  end

  resources :gdrives

  resources :settings, :only => [:index, :update, :edit]

  namespace :oldbook do
    resources :categories, :only => [:index, :edit, :update, :show]
    resources :files, :only => [:destroy]
    resources :tasks
  end

  namespace :artelbook do
    resources :categories, :only => [:index, :edit, :update, :show]
    resources :files, :only => [:destroy]
    resources :tasks
  end

  namespace :alib do
    resources :tasks
  end

  namespace :newauction do
    resources :tasks
  end

  namespace :ebay do
    resources :tasks
  end

  namespace :notifi do
    resources :templates
    resources :contents, :only => [:destroy]
  end

  namespace :parse do
    resources :dbs
    resources :tasks
  end

  namespace :avito do
    resources :accounts
    resources :postings
    resources :tasks
    resources :finds
  end

  devise_for :users
  resources :images, :only => [:index, :create]
  resources :roles

  root  'static_page#main'
  post  'beta' => 'feed_back#beta'

  post  'api/avito' => 'api#avito'
  get   'api/avito' => 'api#avito'

  post  'api/test' => 'api#test'
  get   'api/test' => 'api#test'

  post  'tst' => 'api#txt'
  get   'tst' => 'api#txt'

  get   'test' => 'static_page#test'

end

app/models/avito.rb
module Avito
  def self.table_name_prefix
    'avito_'
  end
end

app/models/avito/account.rb
class Avito::Account < ActiveRecord::Base
  belongs_to :user, :class_name => User

  validates :login, presence: true
  validates :pass, presence: true
end

app/models/avito/find.rb
class Avito::Find < ActiveRecord::Base
  belongs_to :user, :class_name => User
end

app/models/avito/posting.rb
class Avito::Posting < ActiveRecord::Base
  belongs_to :user, :class_name => User


  validates :p, presence: true
  validates :e, presence: true
  validates :name, presence: true

  validates :title, presence: true
  validates :description, presence: true
  validates :images,    presence:true
end

app/models/avito/task.rb
class Avito::Task < ActiveRecord::Base

  belongs_to :user, :class_name => User
  belongs_to :gdrive, :class_name => Gdrive
  has_many :avito_tasklogs, :class_name => Avito::Tasklog
  
  belongs_to :notifi_template, :class_name => Notifi::Template, :foreign_key => :notifi_template_id
  
  
  validates :p, presence: true
  validates :name, presence: true

  #validates :e, presence: true
  
end

app/models/avito/tasklog.rb
class Avito::Tasklog < ActiveRecord::Base
  belongs_to :avito_task, :class_name => Avito::Task

end

app/controllers/avito/accounts_controller.rb
class Avito::AccountsController < ApplicationController
  respond_to    :html
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @avito_accounts = Avito::Account.where(:user_id => current_user.id).all
    respond_with(@avito_accounts)
  end

  def show
    if @avito_account.status == 0 || params[:task] == 'test' 
      account_info
    elsif @avito_account.status == 1 && params[:task] == 'post'
      account_post
    else
      respond_with(@avito_account)
    end 
  end

  def new
    @avito_account = Avito::Account.new
    respond_with(@avito_account)
  end

  def edit

  end

  def create
    @avito_account = Avito::Account.new(account_params)
    @avito_account.user = current_user
    if Avito::Account.find_by(:login => account_params[:login]).blank?
      @avito_account.save
      respond_with(@avito_account)
    else
      flash[:notice] = "Укажите другой логин"
      render 'new'
    end
  end

  def update
    @avito_account.status = 0
    @avito_account.update(account_params)
    respond_with(@avito_account)
  end

  def destroy
    @avito_account.destroy
    flash[:notice] = 'Удаленно успешно.'
    redirect_to :controller=>'accounts', :action => 'index'
  end

  private
    def set_account
      @avito_account = Avito::Account.find_by(:id => params[:id], :user_id => current_user.id)
    end

    def account_params
      params.require(:avito_account).permit(:login, :pass, :task)
    end


    ################
    #######XXX######
    ################
    def agent_init
      @agent = Mechanize.new
      true
    end

    def agent_login
      ex = false
      page_login = @agent.get "https://www.avito.ru/profile/login"
      if page_login.form.action == "/profile/login"
        page_login.form.field("login").value    = @avito_account.login
        page_login.form.field("password").value = @avito_account.pass
        page_profile = page_login.form.submit()
        ex = page_profile.uri.path == "/profile"
      end 
      ex
    end

    def account_info
      #fork do
        agent_init
        page_login = @agent.get "https://www.avito.ru/profile/login"
        if page_login.form.action == "/profile/login"
          page_login.form.field("login").value    = @avito_account.login
          page_login.form.field("password").value = @avito_account.pass
          page_profile = page_login.form.submit()

          if page_profile.uri.path == "/profile/login"
            #no auth
            @avito_account.status = 2

          elsif page_profile.uri.path == "/profile"
            #auth ok
            page_settings    = @agent.get "https://www.avito.ru/profile/settings"
            @avito_account.f = {
              "info" => {
                "name"   => page_settings.search("//h1/span[contains(@class,'name')]").text.strip,
                "status" => page_settings.search("//h1/span[contains(@class,'status')]").text.strip                
              }
            }
            @avito_account.status = 1
          end
        else
          #no form
        end
        @avito_account.save
       
        flash[:notice] = 'Добавленно в очередь. Выполнится в течении неслькоих минут.'
        redirect_to :controller=>'accounts', :action => 'show', :id => params[:id]

      #end
    end

    def account_post

      if agent_init && agent_login
        page_profile_active = @agent.get "https://www.avito.ru/profile/items/active"
        page_profile_old    = @agent.get "https://www.avito.ru/profile/items/old"
        @avito_account.f = {
          "info" => @avito_account.f['info'],
          "posts" => {
            "active" => page_profile_active.search("//h3/a").map {|a| Hash[:title ,a.text, :id, a.attribute("href").text.split("_")[-1], :url, a.attribute("href").text]},
            "old"    =>    page_profile_old.search("//h3/a").map {|a| Hash[:title ,a.text, :id, a.attribute("href").text.split("_")[-1], :url, a.attribute("href").text]}
          }
        }

        print @avito_account.f

        @avito_account.save
      end

      flash[:notice] = 'Возможна задержка(1-2мин) при выполнении задания.'
      redirect_to :controller=>'accounts', :action => 'show', :id => params[:id]

    end
end

app/controllers/avito/finds_controller.rb
class Avito::FindsController < ApplicationController
  before_action :set_avito_find, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

  def index
    @avito_finds = current_user.avito_finds.all
    respond_with(@avito_finds)
  end

  def show
    respond_with(@avito_find)
  end

  def new
    @avito_find = Avito::Find.new
    respond_with(@avito_find)
  end

  def edit
  end

  def create
    @avito_find = Avito::Find.new(find_params)
    @avito_find.save
    respond_with(@avito_find)
  end

  def update
    @avito_find.update(find_params)
    respond_with(@avito_find)
  end

  def destroy
    @avito_find.destroy
    respond_with(@avito_find)
  end

  private
    def set_avito_find
      @avito_find = Avito::Find.find(params[:id])
    end

    def avito_find_params
      params.require(:avito_find).permit(:require, :response)
    end
end

app/controllers/avito/postings_controller.rb
class Avito::PostingsController < ApplicationController
  respond_to    :html
  before_action :authenticate_user!
  before_action :set_posting, only: [:show, :edit, :update, :destroy]
  before_action :work_account
  before_action :chek_antigate


  def index
    @avito_postings = Avito::Posting.where(:user_id => current_user.id)
    respond_with(@avito_postings)
  end

  def show
    respond_with(@posting)
  end

  def new
    @avito_posting = Avito::Posting.new
    respond_with(@avito_posting)
  end

  def edit
  end

  def create
    swoop = Proc.new { |k, v| v.delete_if(&swoop) if v.kind_of?(Hash);  v.blank? }
    @posting = Avito::Posting.new(posting_params.delete_if(&swoop))

    @posting.user = current_user
    render :json => {:status=>@posting.save, :result=>@posting}
  end

  def update
    @avito_posting.update(posting_params)
    respond_with(@avito_posting)
  end

  def destroy
    @avito_posting.destroy
    respond_with(@avito_posting)
  end

  private
    def set_posting
      @avito_posting = Avito::Posting.find_by(:id => params[:id], :user_id => current_user.id)
    end


    def work_account
      @work_account = current_user.avito_accounts.where(:status => 1)
      if @work_account.blank?
        flash[:notice] = 'В начале добавте хотя бы один рабочий аккаунт.'
        redirect_to :controller=>'accounts', :action => 'index'
      end
    end

    def chek_antigate
      @antigate_key = current_user.antigate_key
      if @antigate_key.blank?
        flash[:notice] = 'А кто будет гадать капчу? Требуется при перепосте.'
        redirect_to :controller=>'devise_invitable/registrations', :action => 'edit'
      end
    end

    def posting_params_strong
      params.require(:avito_posting).permit(:name, :title, :description, :manager, :price, :images, :count, :user_id, :active, :allow_mail)
    end

    def posting_params
      params.require(:avito_posting).permit(:name, :count, :active, :allow_mail, :interval).tap do |while_listed|
        if params[:action] == "create"
          while_listed[:p] = params[:task][:p]
        end 

        while_listed[:e] = params[:task][:e]

        while_listed[:title]       = params[:avito_posting][:title]
        while_listed[:description] = params[:avito_posting][:description]
        while_listed[:manager]     = params[:avito_posting][:manager]
        while_listed[:price]       = params[:avito_posting][:price]
        while_listed[:images]      = params[:avito_posting][:images]

      end
    end


end

app/controllers/avito/tasks_controller.rb
class Avito::TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  respond_to    :html
  before_action :authenticate_user!
  before_action :notifi_teplates

  def index
    @tasks = Avito::Task.all
    respond_with(@tasks)
  end

  def show
    respond_with(@task)
  end

  def new
    @task = Avito::Task.new
    @notifi_templates = current_user.notifi_templates.where(:active => true)
    respond_with(@task)
  end

  def edit
  end


  def create
    swoop = Proc.new { |k, v| v.delete_if(&swoop) if v.kind_of?(Hash);  v.empty? }
    @task = Avito::Task.new(task_params.delete_if(&swoop))

    @task.user = current_user
    render :json => {:status=>@task.save, :result=>@task}
  end

  def update
    @task.update(task_params_strong)
    respond_with(@task)
  end

  def destroy
    @task.destroy
    respond_with(@task)
  end


  ###-_-_-_###
  private
    def set_task
      @task = Avito::Task.find_by(:id => params[:id])
    end

    def task_params
      params.require(:avito_task).permit(:name, :interval, :active, :notifi_template_id, :q,:gdrive_id).tap do |while_listed|
        while_listed[:p] = params[:task][:p]
        while_listed[:e] = params[:task][:e]
      end
    end

    def task_params_strong
      params.require(:avito_task).permit(:name, :interval, :active, :notifi_template_id, :q, :next_at, :gdrive_id)
    end

    def notifi_teplates
      @notifi_teplates = Notifi::Template.where(:active => true).all.collect {|p| [ p.name, p.id ] }
      @gdrive = Gdrive.where(:enable => true).all.collect {|p| [ p.name, p.id ] }
    end


end

app/helpers/admin/postings_helper.rb
module Admin::PostingsHelper
end

app/helpers/avito/accounts_helper.rb
module Avito::AccountsHelper
end

app/helpers/avito/finds_helper.rb
module Avito::FindsHelper
end

app/helpers/avito/postings_helper.rb
module Avito::PostingsHelper
end

app/views/avito/postings/_form.html.haml
%fieldset
  %legend 
    Загрузка новых фотографий
  %form#my-awesome-dropzone.dropzone{:action => "/images"}
    =hidden_field_tag :authenticity_token, form_authenticity_token
    =hidden_field_tag :img_class, "avito_posting"


= form_for @avito_posting do |f|

  - if @avito_posting.errors.any?
    -flash[:alert] = "<ul>"
    -@avito_posting.errors.full_messages.each do |msg|
      -flash[:alert] += '<li>'+msg+'</li>'
    -flash[:alert] += "</ul>"
  
  %fieldset
    %legend Параметры задачи 
    .row
      .large-6.columns
        .field
          = f.label :name, "Имя задачи"
          = f.text_field :name

        .row
          .large-6.columns
            %label
              Включить задачу
            .switch
              = f.check_box :active
              = f.label :active
          .large-6.columns
            %label
              Разрешить ответы на почту
            .switch
              = f.check_box :allow_mail
              = f.label :allow_mail


      .large-6.columns
        .field
        = f.label :interval do 
          Интервал дней: 
          %span{:id=>"avito_interval"}

        -if params[:action] == "new"
          -@avito_posting.interval = 7

        .range-slider{ :data => { :slider => "",  :options=> "start: 1; end: 60; display_selector: #avito_interval; initial: #{@avito_posting.interval};" } }
          %span.range-slider-handle{:role => "slider", :tabindex => @avito_posting.interval}
          %span.range-slider-active-segment
          = f.hidden_field :interval


        .field
          = label_tag "task[e][type_uniq]", 'Тип уникализации текста'
          - select = @avito_posting.e.blank? || @avito_posting.e['type_uniq'].blank? ? "" : @avito_posting.e['type_uniq'] 
          = select_tag "task[e][type_uniq]", options_for_select([["Два варианта",1], 
                                                   ["Без уникализации (опасненько)",{:disabled => "disabled"}, 0], 
                                                   ["Перестановка предложений",{:disabled => "disabled"}, 2], 
                                                   ["Синонимизация",{:disabled => "disabled"}, 3], 
                                                   ["Рандомный выбор", {:disabled => "disabled"}, 4]], select)

        .field
          - select = @avito_posting.e.blank? || @avito_posting.e['account_id'].blank? ? "" : @avito_posting.e['account_id'] 
          = f.label "task[e][account_id]", 'Аккаунт для постинга'
          = select_tag "task[e][account_id]", options_from_collection_for_select(@work_account, "id", "login", select)
    .row
      .large-12.columns
        .field
          -if @avito_posting.images.blank?
            - option = options_from_collection_for_select(Image.where(:user_id => current_user.id), "id", "name", [])
          -else
            - option = options_from_collection_for_select(Image.where(:user_id => current_user.id), "id", "name", @avito_posting.images)
          
          = label_tag "avito_posting[images][]", "Загруженные изображения"
          = select_tag "avito_posting[images][]", option, :class => "images-select", :multiple=>"",  :data => {:placeholder => "Выберите загруженную фотографию"}
          

  -if params[:action] == "new"
    %fieldset
      %legend Регион/категория 
      .row
        .large-6.columns
          %label 
            Выберите регион
          %select#avito_main_regions{:name => "task[p][locationId]"}
          #avito_sub_regions
        .large-6.columns
          %label
            Категория
          %select#avito_main_cs
          %label
            Подкатегория
          %select#avito_sub_cs{:disabled => "", :name => 'task[p][categoryId]'}
      .row
        .large-12.cloumns
          %span{:class => "sub-params", :id => "subl_location"}      
      .row#avito_search_params

  //-if @avito_posting.id.nil?
  %ul.tabs{"data-tab" => "", :role => "tablist"}
    %li.tab-title.active{:role => "presentational"}
      %a{"aria-selected" => "true",  :controls => "panel2-1", :href => "#panel2-1", :role => "tab", :tabindex => "0"} Вариант 1
    %li.tab-title{:role => "presentational"}
      %a{"aria-selected" => "false", :controls => "panel2-2", :href => "#panel2-2", :role => "tab", :tabindex => "0"} Вариант 2
  //-else
  //  aa


  .tabs-content
    %section#panel2-1.content.active{"aria-hidden" => "false", :role => "tabpanel"}
      =render :partial => "posting_form", :locals => {:i => 0}
    %section#panel2-2.content{"aria-hidden" => "true", :role => "tabpanel"}
      =render :partial => "posting_form", :locals => {:i => 1}

  .actions
    .button-group.radius.stack
      %li
        =f.button :type => 'submit', :class=>"button success expand", :id => 'posting_submit' do 
          Сохранить
      %li
        = link_to avito_postings_path, :class=> "button expand secondary" do
          Назад

app/views/avito/postings/_posting_form.html.haml
.row
  .large-10.columns
    .field
    = label_tag "avito_posting[title][#{i}]", "Заголовок"
    = text_field_tag "avito_posting[title][#{i}]", params[:action]=="edit" && !@avito_posting.title.nil? ? @avito_posting.title["#{i}"] : ""
  .large-2.columns
    .field
    = label_tag "avito_posting[price][#{i}]", "Цена"
    = number_field_tag "avito_posting[price][#{i}]", params[:action]=="edit" && !@avito_posting.price.nil? ?  @avito_posting.price["#{i}"] : ""

.field
  = label_tag "avito_posting[description][#{i}]", "Описание"
  = text_area_tag "avito_posting[description][#{i}]", params[:action]=="edit" && !@avito_posting.description.nil? ? @avito_posting.description["#{i}"] : "", :maxlength=>"3000", :rows=>10

app/views/avito/postings/edit.html.haml
%h1 
  Авито автопостинг
  %small
    редактирование

#avito-dash.hide ok


.row
  .large-12.columns
    = render 'form'

//= link_to 'Show', @avito_posting
//\|
//= link_to 'Back', avito_postings_path

app/views/avito/postings/index.html.haml
-if @avito_postings.blank?
  %h1 Задач не обнаруженно
  %p Автоматическое отправление обьявлений на авито.  

-else
  %h1 
    Список задач постинга
    %small 
      %a{:href=>"http://info.0liva.ru/avito_posting"} [?]


  %table{:width=>"100%"}
    %thead
      %tr
        %th Имя задачи
        %th Автивность
        %th Обновленна
        %th Следующий запуск        
        %th Id
        %th
        %th
        %th


    %tbody
      - @avito_postings.each do |avito_posting|
        %tr
          %td= avito_posting.name
          %td= avito_posting.active ? "Да" : "Нет"
          %td= avito_posting.updated_at
          %td= avito_posting.next_at
          %td
            -if avito_posting.s['item_id'].nil?

            -else
              = link_to avito_posting.s['item_id'], "https://avito.ru/#{avito_posting.s['item_id']}", :target => "_blank"
          %td= link_to 'Инфо', avito_posting
          %td= link_to 'Редакировать', edit_avito_posting_path(avito_posting)
          %td= link_to 'Удалить', avito_posting, :method => :delete, :data => { :confirm => 'Вы уверенны?' }


= link_to new_avito_posting_path, :class=>"button success expand" do 
  Новая задача 

app/views/avito/postings/new.html.haml
%h1 
  Авито автопостинг
  %small
    новая задача

#avito-dash.hide ok

.row
  .large-12.columns
    = render 'form'

  
//= link_to 'Back', avito_postings_path

app/views/avito/postings/show.html.haml
%p#notice= notice

%h1= @avito_posting.name

%b Заголовки обьявлений:
%ul
  - @avito_posting.title.each do |k,v|
    %li 
      =v

%b Заголовки обьявлений:
%ul
  - @avito_posting.description.each do |k,v|
    %li 
      =v

%b Цены:
%ul
  - @avito_posting.price.each do |k,v|
    %li 
      =v
%p
  %b Интервал повторения в днях:
  = @avito_posting.interval   

%p
  %b Активность:
  = @avito_posting.active ? "Да" : "Нет"

%p
  %b Сработок задания:
  = @avito_posting.count

%p
  %b Принимать ответы на почту:
  = @avito_posting.active ? "Да" : "Нет"

%p
  %b Запланированно на:
  = @avito_posting.next_at



-if User.last.role_id >= 1024

  %p
    %b P:
    = @avito_posting.p
  %p
    %b E:
    = @avito_posting.e
  %p
    %b S:
    = @avito_posting.s




-unless @avito_posting.images.blank? 
  %h2 Изображения
  -Image.find(@avito_posting.images).each do |image|
    %img{:src=>"/image/#{current_user.id}/#{image.img_hash}.#{image.img_type}", :width=> "100px"}

%hr
%ul.button-group.radius.stack
  %li
    = link_to avito_postings_path, :class=> "button expand secondary" do
      Назад
  %li
    = link_to edit_avito_posting_path(@avito_posting), :class=>"button success" do 
      Редактировать