config/routes.rb
Rails.application.routes.draw do

  namespace :iml do
    resources :points, :only => [:index, :update, :edit, :show]
    resources :cities, :only => [:index, :update, :edit, :show]
  end

  namespace :bidspirit do
    resources :tasks
  end

  resources :gdrives

  resources :settings, :only => [:index, :update, :edit]

  namespace :oldbook do
    resources :categories, :only => [:index, :edit, :update, :show]
    resources :files, :only => [:destroy]
    resources :tasks
  end

  namespace :artelbook do
    resources :categories, :only => [:index, :edit, :update, :show]
    resources :files, :only => [:destroy]
    resources :tasks
  end

  namespace :alib do
    resources :tasks
  end

  namespace :newauction do
    resources :tasks
  end

  namespace :ebay do
    resources :tasks
  end

  namespace :notifi do
    resources :templates
    resources :contents, :only => [:destroy]
  end

  namespace :parse do
    resources :dbs
    resources :tasks
  end

  namespace :avito do
    resources :accounts
    resources :postings
    resources :tasks
    resources :finds
  end

  devise_for :users
  resources :images, :only => [:index, :create]
  resources :roles

  root  'static_page#main'
  post  'beta' => 'feed_back#beta'

  post  'api/avito' => 'api#avito'
  get   'api/avito' => 'api#avito'

  post  'api/test' => 'api#test'
  get   'api/test' => 'api#test'

  post  'tst' => 'api#txt'
  get   'tst' => 'api#txt'

  get   'test' => 'static_page#test'

end

app/models/alib/task.rb
class Alib::Task < ActiveRecord::Base
  belongs_to :user, :class_name => User
  belongs_to :gdrive, :class_name => Gdrive
  has_many :alib_tasklogs, :class_name => Alib::Tasklog
  
  belongs_to :notifi_template, :class_name => Notifi::Template, :foreign_key => :notifi_template_id

  validates :name, presence: true
end

app/models/artelbook/task.rb
class Artelbook::Task < ActiveRecord::Base

  has_many :products, :class_name => Artelbook::Product
  has_many :files,    :class_name => Artelbook::File

end

app/models/avito.rb
module Avito
  def self.table_name_prefix
    'avito_'
  end
end

app/models/avito/account.rb
class Avito::Account < ActiveRecord::Base
  belongs_to :user, :class_name => User

  validates :login, presence: true
  validates :pass, presence: true
end

app/models/avito/find.rb
class Avito::Find < ActiveRecord::Base
  belongs_to :user, :class_name => User
end

app/models/avito/posting.rb
class Avito::Posting < ActiveRecord::Base
  belongs_to :user, :class_name => User


  validates :p, presence: true
  validates :e, presence: true
  validates :name, presence: true

  validates :title, presence: true
  validates :description, presence: true
  validates :images,    presence:true
end

app/models/avito/task.rb
class Avito::Task < ActiveRecord::Base

  belongs_to :user, :class_name => User
  belongs_to :gdrive, :class_name => Gdrive
  has_many :avito_tasklogs, :class_name => Avito::Tasklog
  
  belongs_to :notifi_template, :class_name => Notifi::Template, :foreign_key => :notifi_template_id
  
  
  validates :p, presence: true
  validates :name, presence: true

  #validates :e, presence: true
  
end

app/models/avito/tasklog.rb
class Avito::Tasklog < ActiveRecord::Base
  belongs_to :avito_task, :class_name => Avito::Task

end

app/models/oldbook/task.rb
class Oldbook::Task < ActiveRecord::Base

  has_many :products, :class_name => Oldbook::Product
  has_many :files,    :class_name => Oldbook::File

end

app/controllers/alib/tasks_controller.rb
class Alib::TasksController < ApplicationController
  before_action :set_alib_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :notifi_teplates


  respond_to :html

  def index
    @alib_tasks = Alib::Task.all
    respond_with(@alib_tasks)
  end

  def show
    respond_with(@alib_task)
  end

  def new
    @alib_task = Alib::Task.new
    respond_with(@alib_task)
  end

  def edit
  end

  def create
    @alib_task = Alib::Task.new(task_params)
    @alib_task.save
    respond_with(@alib_task)
  end

  def update
    @alib_task.update(task_params)
    respond_with(@alib_task)
  end

  def destroy
    @alib_task.destroy
    respond_with(@alib_task)
  end

  private
    def set_alib_task
      @alib_task = Alib::Task.find(params[:id])
    end

    def task_params
      params.require(:alib_task).permit(:name, :q, :interval, :active, :next_at, :notifi_template_id, :shop, :gdrive_id)
    end

    def notifi_teplates
      @notifi_teplates = Notifi::Template.where(:active => true).all.collect {|p| [ p.name, p.id ] }
      @gdrive = Gdrive.where(:enable => true).all.collect {|p| [ p.name, p.id ] }
    end
end

app/controllers/artelbook/tasks_controller.rb
class Artelbook::TasksController < ApplicationController
  before_action :set_Artelbook_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

  def index
    @artelbook_tasks = Artelbook::Task.all

    if params[:task] == "run"
      run
      redirect_to action: 'index'
    else
      respond_with(@artelbook_tasks)
    end

  end

  def show
    respond_with(@artelbook_task)
  end

  def new
    @artelbook_task = Artelbook::Task.new
    respond_with(@artelbook_task)
  end

  def edit
  end

  def create
    @artelbook_task = Artelbook::Task.new(task_params)
    @artelbook_task.save
    respond_with(@artelbook_task)
  end

  def update
    @artelbook_task.update(task_params)
    respond_with(@artelbook_task)
  end

  def destroy
    @artelbook_task.destroy
    respond_with(@artelbook_task)
  end

  private
    def set_Artelbook_task
      @artelbook_task = Artelbook::Task.find(params[:id])
    end

    def task_params
      params.require(:artelbook_task).permit(:name, :path, :enable, :price_ratio, :sku_regex, :title_exclude)
    end

    def run
      unless File.exist?('tmp/artelbook_task')
        File.write('tmp/artelbook_task','')
      end
    end
end

app/controllers/avito/accounts_controller.rb
class Avito::AccountsController < ApplicationController
  respond_to    :html
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @avito_accounts = Avito::Account.where(:user_id => current_user.id).all
    respond_with(@avito_accounts)
  end

  def show
    if @avito_account.status == 0 || params[:task] == 'test' 
      account_info
    elsif @avito_account.status == 1 && params[:task] == 'post'
      account_post
    else
      respond_with(@avito_account)
    end 
  end

  def new
    @avito_account = Avito::Account.new
    respond_with(@avito_account)
  end

  def edit

  end

  def create
    @avito_account = Avito::Account.new(account_params)
    @avito_account.user = current_user
    if Avito::Account.find_by(:login => account_params[:login]).blank?
      @avito_account.save
      respond_with(@avito_account)
    else
      flash[:notice] = "Укажите другой логин"
      render 'new'
    end
  end

  def update
    @avito_account.status = 0
    @avito_account.update(account_params)
    respond_with(@avito_account)
  end

  def destroy
    @avito_account.destroy
    flash[:notice] = 'Удаленно успешно.'
    redirect_to :controller=>'accounts', :action => 'index'
  end

  private
    def set_account
      @avito_account = Avito::Account.find_by(:id => params[:id], :user_id => current_user.id)
    end

    def account_params
      params.require(:avito_account).permit(:login, :pass, :task)
    end


    ################
    #######XXX######
    ################
    def agent_init
      @agent = Mechanize.new
      true
    end

    def agent_login
      ex = false
      page_login = @agent.get "https://www.avito.ru/profile/login"
      if page_login.form.action == "/profile/login"
        page_login.form.field("login").value    = @avito_account.login
        page_login.form.field("password").value = @avito_account.pass
        page_profile = page_login.form.submit()
        ex = page_profile.uri.path == "/profile"
      end 
      ex
    end

    def account_info
      #fork do
        agent_init
        page_login = @agent.get "https://www.avito.ru/profile/login"
        if page_login.form.action == "/profile/login"
          page_login.form.field("login").value    = @avito_account.login
          page_login.form.field("password").value = @avito_account.pass
          page_profile = page_login.form.submit()

          if page_profile.uri.path == "/profile/login"
            #no auth
            @avito_account.status = 2

          elsif page_profile.uri.path == "/profile"
            #auth ok
            page_settings    = @agent.get "https://www.avito.ru/profile/settings"
            @avito_account.f = {
              "info" => {
                "name"   => page_settings.search("//h1/span[contains(@class,'name')]").text.strip,
                "status" => page_settings.search("//h1/span[contains(@class,'status')]").text.strip                
              }
            }
            @avito_account.status = 1
          end
        else
          #no form
        end
        @avito_account.save
       
        flash[:notice] = 'Добавленно в очередь. Выполнится в течении неслькоих минут.'
        redirect_to :controller=>'accounts', :action => 'show', :id => params[:id]

      #end
    end

    def account_post

      if agent_init && agent_login
        page_profile_active = @agent.get "https://www.avito.ru/profile/items/active"
        page_profile_old    = @agent.get "https://www.avito.ru/profile/items/old"
        @avito_account.f = {
          "info" => @avito_account.f['info'],
          "posts" => {
            "active" => page_profile_active.search("//h3/a").map {|a| Hash[:title ,a.text, :id, a.attribute("href").text.split("_")[-1], :url, a.attribute("href").text]},
            "old"    =>    page_profile_old.search("//h3/a").map {|a| Hash[:title ,a.text, :id, a.attribute("href").text.split("_")[-1], :url, a.attribute("href").text]}
          }
        }

        print @avito_account.f

        @avito_account.save
      end

      flash[:notice] = 'Возможна задержка(1-2мин) при выполнении задания.'
      redirect_to :controller=>'accounts', :action => 'show', :id => params[:id]

    end
end

app/controllers/avito/finds_controller.rb
class Avito::FindsController < ApplicationController
  before_action :set_avito_find, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

  def index
    @avito_finds = current_user.avito_finds.all
    respond_with(@avito_finds)
  end

  def show
    respond_with(@avito_find)
  end

  def new
    @avito_find = Avito::Find.new
    respond_with(@avito_find)
  end

  def edit
  end

  def create
    @avito_find = Avito::Find.new(find_params)
    @avito_find.save
    respond_with(@avito_find)
  end

  def update
    @avito_find.update(find_params)
    respond_with(@avito_find)
  end

  def destroy
    @avito_find.destroy
    respond_with(@avito_find)
  end

  private
    def set_avito_find
      @avito_find = Avito::Find.find(params[:id])
    end

    def avito_find_params
      params.require(:avito_find).permit(:require, :response)
    end
end

app/controllers/avito/postings_controller.rb
class Avito::PostingsController < ApplicationController
  respond_to    :html
  before_action :authenticate_user!
  before_action :set_posting, only: [:show, :edit, :update, :destroy]
  before_action :work_account
  before_action :chek_antigate


  def index
    @avito_postings = Avito::Posting.where(:user_id => current_user.id)
    respond_with(@avito_postings)
  end

  def show
    respond_with(@posting)
  end

  def new
    @avito_posting = Avito::Posting.new
    respond_with(@avito_posting)
  end

  def edit
  end

  def create
    swoop = Proc.new { |k, v| v.delete_if(&swoop) if v.kind_of?(Hash);  v.blank? }
    @posting = Avito::Posting.new(posting_params.delete_if(&swoop))

    @posting.user = current_user
    render :json => {:status=>@posting.save, :result=>@posting}
  end

  def update
    @avito_posting.update(posting_params)
    respond_with(@avito_posting)
  end

  def destroy
    @avito_posting.destroy
    respond_with(@avito_posting)
  end

  private
    def set_posting
      @avito_posting = Avito::Posting.find_by(:id => params[:id], :user_id => current_user.id)
    end


    def work_account
      @work_account = current_user.avito_accounts.where(:status => 1)
      if @work_account.blank?
        flash[:notice] = 'В начале добавте хотя бы один рабочий аккаунт.'
        redirect_to :controller=>'accounts', :action => 'index'
      end
    end

    def chek_antigate
      @antigate_key = current_user.antigate_key
      if @antigate_key.blank?
        flash[:notice] = 'А кто будет гадать капчу? Требуется при перепосте.'
        redirect_to :controller=>'devise_invitable/registrations', :action => 'edit'
      end
    end

    def posting_params_strong
      params.require(:avito_posting).permit(:name, :title, :description, :manager, :price, :images, :count, :user_id, :active, :allow_mail)
    end

    def posting_params
      params.require(:avito_posting).permit(:name, :count, :active, :allow_mail, :interval).tap do |while_listed|
        if params[:action] == "create"
          while_listed[:p] = params[:task][:p]
        end 

        while_listed[:e] = params[:task][:e]

        while_listed[:title]       = params[:avito_posting][:title]
        while_listed[:description] = params[:avito_posting][:description]
        while_listed[:manager]     = params[:avito_posting][:manager]
        while_listed[:price]       = params[:avito_posting][:price]
        while_listed[:images]      = params[:avito_posting][:images]

      end
    end


end

app/controllers/avito/tasks_controller.rb
class Avito::TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  respond_to    :html
  before_action :authenticate_user!
  before_action :notifi_teplates

  def index
    @tasks = Avito::Task.all
    respond_with(@tasks)
  end

  def show
    respond_with(@task)
  end

  def new
    @task = Avito::Task.new
    @notifi_templates = current_user.notifi_templates.where(:active => true)
    respond_with(@task)
  end

  def edit
  end


  def create
    swoop = Proc.new { |k, v| v.delete_if(&swoop) if v.kind_of?(Hash);  v.empty? }
    @task = Avito::Task.new(task_params.delete_if(&swoop))

    @task.user = current_user
    render :json => {:status=>@task.save, :result=>@task}
  end

  def update
    @task.update(task_params_strong)
    respond_with(@task)
  end

  def destroy
    @task.destroy
    respond_with(@task)
  end


  ###-_-_-_###
  private
    def set_task
      @task = Avito::Task.find_by(:id => params[:id])
    end

    def task_params
      params.require(:avito_task).permit(:name, :interval, :active, :notifi_template_id, :q,:gdrive_id).tap do |while_listed|
        while_listed[:p] = params[:task][:p]
        while_listed[:e] = params[:task][:e]
      end
    end

    def task_params_strong
      params.require(:avito_task).permit(:name, :interval, :active, :notifi_template_id, :q, :next_at, :gdrive_id)
    end

    def notifi_teplates
      @notifi_teplates = Notifi::Template.where(:active => true).all.collect {|p| [ p.name, p.id ] }
      @gdrive = Gdrive.where(:enable => true).all.collect {|p| [ p.name, p.id ] }
    end


end

app/controllers/bidspirit/tasks_controller.rb
class Bidspirit::TasksController < ApplicationController
  before_action :set_bidspirit_task, only: [:show, :edit, :update, :destroy]
  before_action :notifi_teplates
  respond_to :html

  def index
    @bidspirit_tasks = Bidspirit::Task.all
    respond_with(@bidspirit_tasks)
  end

  def show
    respond_with(@bidspirit_task)
  end

  def new
    @bidspirit_task = Bidspirit::Task.new
    respond_with(@bidspirit_task)
  end

  def edit
  end

  def create
    @bidspirit_task = Bidspirit::Task.new(task_params)
    @bidspirit_task.save
    respond_with(@bidspirit_task)
  end

  def update
    @bidspirit_task.update(task_params)
    respond_with(@bidspirit_task)
  end

  def destroy
    @bidspirit_task.destroy
    respond_with(@bidspirit_task)
  end

  private
    def set_bidspirit_task
      @bidspirit_task = Bidspirit::Task.find(params[:id])
    end

    def task_params
      params.require(:bidspirit_task).permit(:name, :stat, :q, :count, :interval, :active, :counter, :p, :e, :notifi_template_id, :next_at, :gdrive_id)
    end

    def notifi_teplates
      @notifi_teplates = Notifi::Template.where(:active => true).all.collect {|p| [ p.name, p.id ] }
      @gdrive = Gdrive.where(:enable => true).all.collect {|p| [ p.name, p.id ] }
    end


end

app/controllers/ebay/tasks_controller.rb
class Ebay::TasksController < ApplicationController
  before_action :set_ebay_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :notifi_teplates


  respond_to :html

  def index
    @ebay_tasks = Ebay::Task.all
    respond_with(@ebay_tasks)
  end

  def show
    respond_with(@ebay_task)
  end

  def new
    @ebay_task = Ebay::Task.new()
    respond_with(@ebay_task)
  end

  def edit
  end

  def create
    @ebay_task = Ebay::Task.new(task_params)
    @ebay_task.user_id = current_user.id
    @ebay_task.save
    respond_with(@ebay_task)
  end

  def update
    @ebay_task.update(task_params)
    respond_with(@ebay_task)
  end

  def destroy
    @ebay_task.destroy
    respond_with(@ebay_task)
  end

  private
    def set_ebay_task
      @ebay_task = Ebay::Task.find(params[:id])
    end

    def task_params
      params.require(:ebay_task).permit(:name, :q, :interval, :active, :next_at, :notifi_template_id, :gdrive_id)
    end

    def notifi_teplates
      @notifi_teplates = Notifi::Template.where(:active => true).all.collect {|p| [ p.name, p.id ] }
      @gdrive = Gdrive.where(:enable => true).all.collect {|p| [ p.name, p.id ] }
    end

end

app/views/avito/tasks/_form.html.haml
= form_for @task do |f|


  - if @task.errors.any?
    -flash[:alert] = "<ul>"
    -@task.errors.full_messages.each do |msg|
      -flash[:alert] += '<li>'+msg+'</li>'
    -flash[:alert] += "</ul>"


  %fieldset
    %legend Параметры Поиска
    .row
      .large-12.columns
        = f.label :name
        = f.text_field :name, :placeholder => "Имя задачи"

      .large-12.columns
        = f.label :q do
          Фраза для поиска
          %small
            (проверяется только первая)
        = f.text_area :q, :placeholder => "Список запросов для поиска Каждый запрос с новой стороки"

    .row
      .large-6.columns
        %label
          Выберите регион
        %select#avito_main_regions{:name => "task[p][locationId]"}

        /ajax add selects
        #avito_sub_regions

      .large-6.columns
        %label
          Категория
        %select#avito_main_cs

        %label
          Подкатегория
        %select#avito_sub_cs{:disabled => "", :name => 'task[p][categoryId]'}
    .row
      .large-12.cloumns
        %span{:class => "sub-params", :id => "subl_location"}

    .row#avito_search_params


  /ajax add params
  %fieldset
    %legend Действие на новые сообщения

    %label{:for => "e_email"} Email(сразу)
    %input#e_email{:name => "task[e][email]", :placeholder => "Укажите свою почту", :type => "text"}/


    = f.label :notifi_template_id do
      Шаблон нотификации
    =f.select :notifi_template_id , @notifi_teplates, {include_blank: t('none')}

    .row
      .large-12.columns
        = f.label :gdrive_id do
          Включить заспросы из google doc
        =f.select :gdrive_id , @gdrive, {include_blank: t('none')}

    /%label{:for => "e_growl_ip"}
    /  Growl
    /  %a{:href => "http://info.0liva.ru/growl"} ?
    /%input#e_growl_ip{:name => "task[e][growl][host]", :placeholder => "Публичный адрес:порт", :type => "text"}/
    /%input#e_growl_pw{:name => "task[e][growl][pass]", :placeholder => "Укажите пароль",       :type => "text"}/

    /%label{:for => "e_http"}
    /  HTTP запрос
    /  %a{:href => "http://info.0liva.ru/http_post"} ?
    /%input#e_http{:name => "task[e][url]", :placeholder => "Укажите URL", :type => "text"}/

  %fieldset
    %legend Переодичность

    .row
      .large-6.columns
        = f.label :interval do
          Интервал
          %span{:id=>"avito_interval"}
          Мин.


        =f.range_field :interval, in:10..44640, step:30

      .large-6.columns
        %label
          Включить задачу
        .switch
          = f.check_box :active, {:checked => "", :class => 'switch-input'}
          = f.label :active, {:class => 'switch-paddle'} do
            %span{:class=>"show-for-sr"}
              Активно

    .row
      .large-12.columns
        .date
          = f.label :next_at do
            Следующий запуск UTC
          =f.datetime_select :next_at

  %hr

  %ul.stack.button-group
    = link_to avito_tasks_path, :class => 'button secondary' do
      Назад

    = link_to "#", :class=>"button alert", :id => 'bnt-test-task' do
      Проверка

    =f.button :class=>"button success", :id => 'task_submit', :disabled=>"" do
      Сохранить

app/views/avito/tasks/edit.html.haml
%h1 Редактирование задачи

= form_for @task do |f|

  =f.hidden_field :p, :value => "{}"
  =f.hidden_field :e, :value => "{}"

  - if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg

  %fieldset

    .row
      .large-12.columns
        = f.label :name
        = f.text_field :name, :placeholder => "Имя задачи"
    .row
      .large-12.columns
        = f.label :q do
          Список поисковых запрос
        = f.text_area :q, :placeholder => "Список поисковых запрос"

    .row
      .large-12.columns
        = f.label :notifi_template_id do
          Шаблон нотификации
        =f.select :notifi_template_id , @notifi_teplates, {include_blank: t('none')}

    .row
      .large-12.columns
        = f.label :gdrive_id do
          Включить заспросы из google doc
        =f.select :gdrive_id , @gdrive, {include_blank: t('none')}

  %fieldset
    %legend Переодичность

    .row
      .large-6.columns
        = f.label :interval do
          Интервал
          %span{:id=>"avito_interval"}
            = @task.interval
          Мин.

        =f.range_field :interval, in:10..44640, step:30
        .date
          = f.label :next_at do
            Следующий запуск UTC
          =f.datetime_select :next_at


      .large-6.columns
        %label
          Включить задачу
        .switch
          = f.check_box :active, {:class => 'switch-input'}
          = f.label :active, {:class => 'switch-paddle'} do
            %span{:class=>"show-for-sr"}
              Активно

  %ul.stack.button-group
    %li
      = link_to avito_tasks_path, :class => 'button secondary ' do
        Назад
    %li
      =f.button :class=>"button success" do
        Сохранить

app/views/avito/tasks/index.html.haml
%table{:role => 'grid', :summary => "Задачи для #{current_user.email}", :width=>"100%"}
  %caption
    Задачи для 
    = current_user.email
  %thead 
    %tr
      %th Название
      %th Интервал
      %th Активность
      %th Прошло

      %th
      %th

  - @tasks.each do |task|
    %tr
      %td
        =link_to task do
          = task.name
    
      %td= task.interval
      %td= task.active ? "Вкл" : "Выкл"
      %td= time_ago_in_words(I18n.l task.updated_at) 

      %td= link_to 'Править', edit_avito_task_path(task)
      %td= link_to 'Удалить', avito_task_path(task), :method => :delete, :data => { :confirm => 'Are you sure?' }


= link_to new_avito_task_path, :class => "button expand success" do
  Новая задача

app/views/avito/tasks/new.html.haml
%h1 Новая задача

#avito-dash.hide ok

.row
  .large-6.columns
    = render 'form'
  .large-6.columns
    %h4 Результаты проверки
    #avito_search_result
    

app/views/avito/tasks/show.html.haml
%p#notice= notice

%h1 Подробная информация


%p
  %b Название:
  = @task.name
%p
  %b Интервал в минутах:
  = @task.interval
%p
  %b Активность:
  = @task.active ? "Да" : "Нет"

%p
  %b Колличество обьявлений на авито:
  = @task.count

%p
  %b Обработанно:
  = @task.avito_tasklogs.count

%p
  %b Время следующего запуска:
  = @task.next_at

%p
  %b Задача созданна
  = @task.created_at

%p
  %b Задача Обновленна
  = @task.updated_at


= link_to avito_tasks_path, :class => 'button secondary' do  
  Назад